### ISSUE TITLE
Error: Cannot find module 'fabric-network'

### ISSUE THREAD

**Issue by ThejasP1997** [IBM/blockchainbean2#10]
![image](https://user-images.githubusercontent.com/24254103/56066944-f184ca80-5d96-11e9-98db-cfa768211df9.png)
I'm getting this error. How to overcome it??

**Comment by horeaporutiu** [comment]
npm install is the answer! run npm install in that directory!

**Comment by horeaporutiu** [comment]
Let me know if that fixes it!

**Comment by ThejasP1997** [comment]
Thank you. It helped me to solve the error. But when I try to run "node query.js", I'm getting "Error: Failed to connect before deadline URL" error.   Please look into the image.
![image](https://user-images.githubusercontent.com/24254103/56074742-1bf57880-5dd5-11e9-8904-ee4746237c86.png)

**Comment by ThejasP1997** [comment]
Thank you. It worked. 
But when I try to run "$node query.js", I'm getting
"Error: Failed to connect before deadline URL" error.   Please look into the image & help me solve the error.
![image](https://user-images.githubusercontent.com/24254103/56074742-1bf57880-5dd5-11e9-8904-ee4746237c86.png)

**Comment by horeaporutiu** [comment]
@ThejasP1997 this is likely a problem with your connection profile. Are you using the cloud network, or running this locally?

**Comment by horeaporutiu** [comment]
@ThejasP1997 I have replicated the problem and working to solve it now.

**Comment by horeaporutiu** [comment]
@ThejasP1997 I have now fixed the problem. If you want to try it, you would just have to clone the latest code, and everything should be working as expected.

**Comment by ash7594** [comment]
Closing Thread as problem is resolved

**Comment by ManpreetSingh28** [comment]
> @ThejasP1997 I have now fixed the problem. If you want to try it, you would just have to clone the latest code, and everything should be working as expected.
> 
> Note that if you already have a Kubernetes cluster + IBM Blockchain Platform running, you will need to delete those services, and then create new ones and create the components again when using the latest updated code.

Hello,
I am trying to debugging but it on Local Network in IBM Blockchain Platform but it shows the below error:

![fabric shim error](https://user-images.githubusercontent.com/66887422/90616767-76a1ae80-e22b-11ea-8c3a-e8bc0992468a.PNG)

Moreover it also shows this:
![fabric shim error 2](https://user-images.githubusercontent.com/66887422/90616903-a6e94d00-e22b-11ea-88d9-ec41b722a640.PNG)

Please help me in removing this error! Much Appreciated!
