### ISSUE TITLE
with npm start i am getting these errors

### ISSUE THREAD

**Issue by hemanthsaimanne** [IBM/blockchainbean2#17]

**Comment by hemanthsaimanne** [comment]
> beanclient@1.0.0 prestart /home/hemanthsai/Downloads/blockchainbean2/web-app
> npm run build


> beanclient@1.0.0 build /home/hemanthsai/Downloads/blockchainbean2/web-app
> lb-tsc es2017 --outDir dist

error TS5042: Option 'project' cannot be mixed with source files on a command line.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! beanclient@1.0.0 build: `lb-tsc es2017 --outDir dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the beanclient@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hemanthsai/.npm/_logs/2020-02-09T09_40_58_449Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! beanclient@1.0.0 prestart: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the beanclient@1.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hemanthsai/.npm/_logs/2020-02-09T09_40_58_477Z-debug.log

**Comment by horeaporutiu** [comment]
@hemanthsaimanne is this on Ubutntu / local version of the app?
